// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cd
Rcpp::List cd(arma::mat X, arma::vec y, double alpha, arma::vec alpha_weights, double tol, int maxiter);
RcppExport SEXP penfmbr_cd(SEXP XSEXP, SEXP ySEXP, SEXP alphaSEXP, SEXP alpha_weightsSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_weights(alpha_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    __result = Rcpp::wrap(cd(X, y, alpha, alpha_weights, tol, maxiter));
    return __result;
END_RCPP
}
