# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cd <- function(X, y, alpha, alpha_weights, tol, maxiter) {
    .Call('penfmbr_cd', PACKAGE = 'penfmbr', X, y, alpha, alpha_weights, tol, maxiter)
}

